steps:
#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/kmitl-hsm/hsm-backend:latest || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/kmitl-hsm/hsm-backend:$COMMIT_SHA',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker push gcr.io/kmitl-hsm/hsm-backend:latest || exit 0'
  ]
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'hsm-backend',
   'hsm-backend=gcr.io/kmitl-hsm/hsm-backend:$COMMIT_SHA',
   '--namespace=hsm'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hsm'
# push images to Google Container Registry with tags
images: [
   'gcr.io/kmitl-hsm/hsm-backend:$COMMIT_SHA',
   'gcr.io/kmitl-hsm/hsm-backend:latest'
  ]