steps:
#step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/kmitl-hsm/hsm-backend:latest || exit 0'
  ]
  id: 'init-django'
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/kmitl-hsm/hsm-static:latest || exit 0'
  ]
  id: 'init-static'
  waitFor: ['-']
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/kmitl-hsm/hsm-backend:$COMMIT_SHA',
   '.'
  ]
  id: 'build-django'
  waitFor: ['init-django']
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/kmitl-hsm/hsm-static:$COMMIT_SHA',
   '-f',
   'static.Dockerfile',
   '.'
  ]
  id: 'build-static'
  waitFor: ['init-static']
#step 3
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker push gcr.io/kmitl-hsm/hsm-backend:latest || exit 0'
  ]
  id: 'push-django'
  waitFor: ['init-django', 'build-django']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker push gcr.io/kmitl-hsm/hsm-static:latest || exit 0'
  ]
  id: 'push-static'
  waitFor: ['init-static', 'build-static']
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'hsm-backend',
   'hsm-backend=gcr.io/kmitl-hsm/hsm-backend:$COMMIT_SHA',
   '--namespace=hsm'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hsm'
  id: 'deploy-django'
  waitFor: ['init-django', 'build-django', 'push-django']
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'hsm-static',
   'hsm-static=gcr.io/kmitl-hsm/hsm-static:$COMMIT_SHA',
   '--namespace=hsm'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hsm'
  id: 'deploy-static'
  waitFor: ['init-static', 'build-static', 'push-static']
# push images to Google Container Registry with tags
images: [
   'gcr.io/kmitl-hsm/hsm-backend:$COMMIT_SHA',
   'gcr.io/kmitl-hsm/hsm-backend:latest',
   'gcr.io/kmitl-hsm/hsm-static:$COMMIT_SHA',
   'gcr.io/kmitl-hsm/hsm-static:latest'
]